[build]
  command = "bun x xyd-js build"
  publish = ".xyd/build/client"

[[redirects]]
  from = "/playground"
  to = "/"
  status = 307
  force = true
  
[[redirects]]
  from = "/docs/"
  to = "/"
  status = 307
  force = true
